### ISSUE TITLE
Different dimensions between model and checkpoint

### ISSUE THREAD

**Issue by Ja1r0** [glample/Arnold#1]
I run this command at the terminal:  
`python arnold.py --scenario deathmatch --wad deathmatch_rockets --n_bots 8 --action_combinations "move_fb;move_lr;turn_lr;attack" --frame_skip 4 --game_features "enemy" --network_type dqn_rnn --recurrence lstm --n_rec_updates 5 --visualize 1 --evaluate 1 --manual_control 1 --reload /home/yang/src/Arnold/pretrained/deathmatch_shotgun.pth`  
And this error occur:
`Traceback (most recent call last):
  File "arnold.py", line 24, in <module>
    parse_game_args(remaining + ['--dump_path', dump_path])
  File "/home/yang/src/Arnold/src/args.py", line 114, in parse_game_args
    module.main(parser, args)
  File "/home/yang/src/Arnold/src/doom/scenarios/deathmatch.py", line 116, in main
    network.module.load_state_dict(reloaded)
  File "/home/yang/local/anaconda3/envs/py35/lib/python3.5/site-packages/torch/nn/modules/module.py", line 519, in load_state_dict
    .format(name, own_state[name].size(), param.size()))
RuntimeError: While copying the parameter named conv.0.weight, whose dimensions in the model are torch.Size([32, 3, 8, 8]) and whose dimensions in the checkpoint are torch.Size([32, 4, 8, 8]).`
Do you know why?Thanks a lot.

**Comment by glample** [comment]
Are you using the command in the `run.sh` script? The problem here is that the reloaded model uses 4 feature maps, while your command creates a model that only requires 3 feature maps (RGB). The 4 feature maps are RGB + one feature maps for the pixels corresponding to enemy bots. Try to add `--labels_mapping "0"` to your command, and see if this helps.
